language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_script:
    - phpenv rehash
    - composer install --dev

script:
    - find ./src/ -name "*.php" -exec php -l {} \;
    - vendor/bin/phpcs --standard=PSR2 --report=full src
    - vendor/bin/phpunit

